name: sum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  math_expressions: ^2.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  linux: 
    generate: true
    icon_size: 128
  macos: 
    generate: true
    icon_size: 128
  windows: 
    generate: true
    icon_size: 48

  image_path: "assets/icon/sum_icon.png"